/*
 * Tencent is pleased to support the open source community by making 蓝鲸加解密Java SDK（crypto-java-sdk） available.
 *
 * Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
 *
 * 蓝鲸加解密Java SDK（crypto-java-sdk） is licensed under the MIT License.
 *
 * License for 蓝鲸加解密Java SDK（crypto-java-sdk）:
 * --------------------------------------------------------------------
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and
 * to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of
 * the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
 * THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tencent.bk.sdk.crypto;

import com.tencent.bk.sdk.crypto.exception.CryptoException;
import com.tencent.bk.sdk.crypto.util.RSAUtil;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.security.KeyPair;
import java.security.PrivateKey;
import java.security.PublicKey;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class RSAUtilTest {

    private static PrivateKey privateKey = null;
    private static PublicKey publicKey = null;

    private static final byte[] EMPTY_MESSAGE = "".getBytes(StandardCharsets.UTF_8);

    private static final byte[] MESSAGE = "test中文符号~!@#$%^&*()_+=-0987654321`[]{};:'\"<>?,./"
        .getBytes(StandardCharsets.UTF_8);

    @BeforeAll
    static void setup() {
        KeyPair keyPair = RSAUtil.genKeyPair();
        privateKey = keyPair.getPrivate();
        publicKey = keyPair.getPublic();
    }

    @Test
    void testEncryptAndDecrypt() {
        // 空值用例
        // key不为空，message为空
        assertThrows(CryptoException.class, () -> RSAUtil.encryptToBytes(publicKey, EMPTY_MESSAGE));
        assertThrows(CryptoException.class, () -> RSAUtil.decryptToBytes(privateKey, EMPTY_MESSAGE));

        // 使用JDK通用接口PublicKey、PrivateKey加解密
        // 一般用例：加密
        byte[] realCipheredMessage = RSAUtil.encryptToBytes(publicKey, MESSAGE);
        // 一般用例：解密
        byte[] normalMessage = RSAUtil.decryptToBytes(privateKey, realCipheredMessage);
        assertArrayEquals(normalMessage, MESSAGE);
    }

}
